import { Octokit } from '@octokit/rest';
import { config } from '../config';
import { saveMeetingSummary } from '../memory/store';

const [owner, repo] = config.GITHUB_REPO.split('/');
const octokit = new Octokit({ auth: config.GITHUB_TOKEN });

const LABEL_NAME = 'plan:needed';

// Ensure label exists (idempotent)
async function ensureLabel(): Promise<void> {
    try {
        await octokit.issues.getLabel({ owner, repo, name: LABEL_NAME });
    } catch {
        await octokit.issues.createLabel({
            owner,
            repo,
            name: LABEL_NAME,
            color: 'e11d48',
            description: 'Awaiting agent-generated plan',
        });
    }
}

export async function createIssue(
    type: string,
    description: string
): Promise<{ number: number; html_url: string }> {
    await ensureLabel();

    const title = `[${type}] ${description.slice(0, 100)}`;
    const body = `## Request\n\n**Type:** \`${type}\`\n\n**Description:**\n${description}\n\n---\n*Submitted via North Orchestrator. Agent meeting in progress...*`;

    const { data } = await octokit.issues.create({
        owner,
        repo,
        title,
        body,
        labels: [LABEL_NAME],
    });

    return { number: data.number, html_url: data.html_url };
}

export async function postPlanToIssue(
    issueNumber: number,
    plan: string,
    atomicTasks: string,
    riskVerdict: string
): Promise<void> {
    const body = `## 🤖 Agent Meeting Complete

## PLAN
${plan}

## ATOMIC TASKS
${atomicTasks}

## RISK VERDICT
${riskVerdict}

---
*Generated by North Orchestrator multi-agent system.*`;

    await octokit.issues.createComment({ owner, repo, issue_number: issueNumber, body });

    // Remove plan:needed label, add plan:ready
    try {
        await octokit.issues.removeLabel({ owner, repo, issue_number: issueNumber, name: LABEL_NAME });
        await octokit.issues.addLabels({
            owner,
            repo,
            issue_number: issueNumber,
            labels: ['plan:ready'],
        });
    } catch (err) {
        console.warn('Label update failed (non-fatal):', (err as Error).message);
    }

    // Save to memory
    await saveMeetingSummary(issueNumber, plan, atomicTasks, riskVerdict);
}

export async function getLastIssue(): Promise<{
    number: number;
    html_url: string;
    state: string;
} | null> {
    const { data } = await octokit.issues.listForRepo({
        owner,
        repo,
        sort: 'created',
        direction: 'desc',
        per_page: 1,
    });
    if (!data.length) return null;
    const issue = data[0];
    return { number: issue.number, html_url: issue.html_url, state: issue.state };
}
